import bcrypt from 'bcryptjs'
const data = {
  users: [
    {
      name: 'Rafael',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Igor',
      email: 'igor@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Ibanez Guitar',
      slug: 'ibanez-guitar',
      category: 'super-estrato',
      image: '/images/guitar1.jpg',
      price: 1200,
      brand: 'Ibanez',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description:
        'Whether in rock, metal, or various genres, the Ibanez stands out with its cutting-edge aesthetics and playability. A favorite among musicians seeking a balance of style and performance.',
      //isFeatured: true,
      banner: '/images/esp-guitar2.png',
    },
    {
      name: 'Fender Stratocaster Guitar',
      slug: 'fender-stratocaster-guitar',
      category: 'strato-caster',
      image: '/images/guitar2.jpg',
      price: 1400,
      brand: 'Fender',
      rating: 4.5,
      numReviews: 8,
      countInStock: 10,
      description:
        'The Fender Stratocaster: iconic electric guitar with a sleek design, renowned for versatility, signature tone, and smooth playability. A classic since the 1950s, favored across genres for its distinctive sound and style.',
      isFeatured: true,
      banner: '/images/esp-guitar.png',
    },
    {
      name: 'Les Paul',
      slug: 'les-paul',
      category: 'les-paul',
      image: '/images/guitar3.jpg',
      price: 5000,
      brand: 'Les Paul',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description:
        'The Gibson SG: iconic double-cutaway electric guitar, celebrated for its lightweight design, comfortable playability, and powerful humbucking pickups. A timeless choice favored by rock and metal musicians since its 1960s debut',
      isFeatured: true,
      banner: '/images/esp-guitar2.png',
    },
    {
      name: 'SG-Guitar',
      slug: 'sg-guitar',
      category: 'SG',
      image: '/images/guitar4.jpg',
      price: 3500,
      brand: 'SG',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description:
        'The SG guitar is a sleek, double-cutaway electric model known for its lightweight design, comfortable playability, and powerful humbucking pickups. Introduced by Gibson in the 1960s, its a favorite among rock and metal musicians for its distinctive look and versatile sound',
      isFeatured: true,
      banner: '/images/esp-guitar3.png',
    },
    {
      name: 'ESP-Guitar',
      slug: 'esp-guitar',
      category: 'ESP',
      image: '/images/guitar5.jpg',
      price: 2500,
      brand: 'ESP',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A guitar for all kinds of tasts',
      //isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'MJ SERIES DINKY',
      slug: 'mj-series-dink',
      category: 'jackson',
      image: '/images/jackson-guitar.jpg',
      price: 4500,
      brand: 'Jackson',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description:
        'Engineered from its inception for high-speed, virtuoso playing, the MJ Series Dinky® DKR features an ergonomically contoured basswood body with sculpted shredders cut heel for easy access to the upper registers.',
      //isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'PRO SERIES SIGNATURE JEFF LOOMIS SOLOIST',
      slug: 'pro-series-signature-jeff-loomis-soloist',
      category: 'jackson',
      image: '/images/jackson-guitar2.jpg',
      price: 4500,
      brand: 'Jackson',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description:
        'Jackson® proudly collaborated with Loomis on a new addition to his signature lineup in the form of the Pro Series Signature Jeff Loomis Soloist™ SL7.',
      //isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'MJ SERIES RHOADS RR24MG',
      slug: 'mj-series-rhoads-rr24mg',
      category: 'Jackson',
      image: '/images/jackson-guitar3.jpg',
      price: 2000,
      brand: 'Jackson',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description:
        'Harkening back to the early 90s when import Jackson® guitars were manufactured exclusively in Japan, we introduce the all-new Jackson MJ Series - an exciting and innovative collection of instruments attentively crafted in Japan. The MJ Series blends Jacksons world-renowned legacy of designing high-performance instruments with an assortment of top-tier features at a competitive price point.',
      //isFeatured: true,
      banner: '/images/banner1.jpg',
    },
  ],
}

export default data
