import bcrypt from 'bcryptjs'
const data = {
  users: [
    {
      name: 'Rafael',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Igor',
      email: 'igor@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Ibanez Guitar',
      slug: 'ibanez-guitar',
      category: 'super-estrato',
      image: '/images/guitar1.jpg',
      price: 70,
      brand: 'Ibanez',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A guitar for all kinds of tasts',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Stratocaster Guitar',
      slug: 'stratocaster-guitar',
      category: 'strato-caster',
      image: '/images/guitar2.jpg',
      price: 80,
      brand: 'Fender',
      rating: 4.5,
      numReviews: 8,
      countInStock: 10,
      description: 'A guitar for who likes blues',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Les Paul',
      slug: 'les-paul',
      category: 'les-paul',
      image: '/images/guitar3.jpg',
      price: 70,
      brand: 'Les Paul',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A guitar for all kinds of tasts',
      isFeatured: true,
      banner: '/images/banner3.jpg',
    },
    {
      name: 'SG-Guitar',
      slug: 'sg-guitar',
      category: 'SG',
      image: '/images/guitar4.jpg',
      price: 70,
      brand: 'SG',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A guitar for all kinds of tasts',
      isFeatured: true,
      banner: '/images/banner4.jpg',
    },
    {
      name: 'ESP-Guitar',
      slug: 'esp-guitar',
      category: 'ESP',
      image: '/images/guitar5.jpg',
      price: 70,
      brand: 'ESP',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A guitar for all kinds of tasts',
      isFeatured: true,
      banner: '/images/banner5.jpg',
    },
  ],
}

export default data
